### PR TITLE
[master < T0410-DX] HotJar fixes

### PR DESCRIPTION
**Pull request by katarinasupe**
- [x]  In [Import data](https://memgraph.com/docs/memgraph/import-data/) we need to put .csv files so that people can download them @kgolubic  - Ticket: [T0416-DX](https://airtable.com/appQDegqRQEeDJr0N/tblQfwMT03DWlHS01/viwDHVvwyewJBw0CP/recOK1nYZHNWw03Vn?blocks=hide)
- [x]  In [Import data](https://memgraph.com/docs/memgraph/import-data/) we should draw the graph that is created with LOAD CSV, import CSV tool and cypherl @katarinasupe 
- [x]  Change Download Hub link in [Installation instructions](https://memgraph.com/docs/memgraph/install-memgraph-on-windows-docker#memgraph-base-image) from [https://memgraph.com/download](https://memgraph.com/download) to [https://memgraph.com/download/#memgraph](https://memgraph.com/download/#memgraph) (add anchor) @katarinasupe 
- [x]  Change Memgraph Installation instructions: Separate Memgraph Platform and its components into separate tabs.
- [x]  Change Concepts to Under the hood @vpavicic 
- [x]  Check rust_example query module @katarinasupe  - Talked with Matak. He says that the Rust example module is not important for the documentation since it’s a dummy example of Rust module to raise Rust awareness. He thinks that it would be good if it’s mentioned somewhere, I suggested how-to guides. → We will leave it at Spellbook for now
- [x] Add placeholder to csv import tool run command @katarinasupe 
- [x] Improve Import data @vpavicic - related to https://github.com/memgraph/docs/pull/287
- [x] improved Memgraph Lab pages @vpavicic

### CODE REVIEW

**Comment by katarinasupe** [comment]
Just mention another PR here if you have making changes there :)

**Review by kgolubic — APPROVED** [review]
I've checked everything. This files can be merged.

**Review by kgolubic — APPROVED** [review]
Everything is ok.

**Comment by katarinasupe** [comment]
@g-despot I added a new version, we just need to figure out how to set links to refer to a current version. Should we merge this and then solve that later on, or do we think we'll figure that out any time soon?

**Pull request merged**
